### ISSUE TITLE
Add release versions to GitHub?

### ISSUE THREAD

**Issue by naltun** [maxhumber/gazpacho#1]
`$ git tag v0.7.2 && git push --tags`  🎉 🎈

I really like this project. I think that adding releases to the repository can help the project grow in popularity. I'd like to see that!

**Comment by maxhumber** [comment]
Hey @naltun, this is a great idea. I'm actually working on version [0.8](https://github.com/maxhumber/gazpacho/tree/0.8) right now, and just enabled tagging on [Travis](https://travis-ci.org/maxhumber/gazpacho) for when the release is ready!

**Comment by naltun** [comment]
Awesome! Good luck! I'll provide any bug reports/feedback as I use the project.

**Comment by maxhumber** [comment]
@naltun [As promised](https://github.com/maxhumber/gazpacho/releases) 🥫

**Comment by naltun** [comment]
👏 🎉
