### ISSUE TITLE
get fails on urls containing unicode characters

### ISSUE THREAD

**Issue by mlehotay** [maxhumber/gazpacho#12]
**Describe the bug**

I get a UnicodeEncodeError when calling  get()  with a URL that contains Unicode characters.

**To Reproduce**
Code to reproduce the behaviour:

```python
from gazpacho import get
url = 'https://worldofwarcraft.com/en-us/character/us/stormrage/drãke'
html = get(url)
```

```
UnicodeEncodeError: 'ascii' codec can't encode character '\xe3' in position 36: ordinal not in range(128)
```

**Expected behavior**

get() should succeed without throwing an exception

**Environment:**

 - OS: [Linux]
 - Version: [e.g. 0.9]

**Comment by maxhumber** [comment]
Thanks for the Issue, Michael! 💃

Fixed in [0.9.1](https://pypi.org/project/gazpacho/0.9.1/)
