### ISSUE TITLE
"first" mode on "find" causes exception if no elements found

### ISSUE THREAD

**Issue by psyonara** [maxhumber/gazpacho#14]
**Describe the bug**
When using the `find` method on the `Soup` class, and there are no results found, an exception is thrown if you used `mode="first"`.

**To Reproduce**
Code to reproduce the behaviour:

```python
from gazpacho import Soup
s = Soup("<p>test</p>")
s.find("a", mode="first")
```

**Expected behavior**
It should return `None`.

**Environment:**
 - OS: Linux - Ubuntu
 - Version: 19.10

**Additional context**
None

**Comment by maxhumber** [comment]
Fixed in [0.9.2](https://github.com/maxhumber/gazpacho/releases/tag/v0.9.2)! Thanks for the Issue!! 🤙
