### ISSUE TITLE
lxml requirement is not installed with gazpacho

### ISSUE THREAD

**Issue by koaning** [maxhumber/gazpacho#15]
**Describe the bug**
It seems that the `lxml` dependency is not install by this package on installation. 

**To Reproduce**
I just pip installed the project and this code (which is on the docs) fails.

```python
from gazpacho import get, Soup
import pandas as pd

url = 'https://www.capfriendly.com/browse/active/2020/salary?p=1'
response = get(url)
soup = Soup(response)
df = pd.read_html(str(soup.find('table')))[0]
print(df[['PLAYER', 'TEAM', 'SALARY', 'AGE']].head(3))
```

This is the error.

```
venv/lib/python3.7/site-packages/pandas/io/html.py in _parser_dispatch(flavor)
    846     else:
    847         if not _HAS_LXML:
--> 848             raise ImportError("lxml not found, please install it")
    849     return _valid_parsers[flavor]
    850 

ImportError: lxml not found, please install it
```

**Expected behavior**

Everything here is fixed with a manual `pip install lxml`. But if `lxml` is a dependency then I would expect it to be installed automatically when `gazpacho` is installed. 

**Environment:**
 - OS: macOS
 - Version: 0.9.2

**Comment by maxhumber** [comment]
Hey Vincent~

Thanks for flagging! The `lxml` dependency is a pandas problem... but I had been meaning to swap out that example and update the README...

Just got it [done](https://github.com/maxhumber/gazpacho/releases/tag/v0.9.3) 💃
