### ISSUE TITLE
Format/Pretty Print can't handle void tags

### ISSUE THREAD

**Issue by maxhumber** [maxhumber/gazpacho#26]
**Describe the bug**

Soup can handle and format matched tags no problem:

```python
from gazpacho import Soup
html = """<ul><li>Item 1</li><li>Item 2</li></ul>"""
Soup(html)
```

Which correctly formats to:

```html
<ul>
  <li>Item 1</li>
  <li>Item 2</li>
</ul>
```

But it can't handle void tags (like img)...

**To Reproduce**

For example, this bit of html:

```python
html = """<ul><li>Item 1</li><li>Item 2</li></ul><img src="image.png">"""
Soup(html)
```

Will fail to format on print:

```html
<ul><li>Item 1</li><li>Item 2</li></ul><img src="image.png">
```

**Expected behavior**

Ideally Soup formats it as:

```html
<ul>
  <li>Item 1</li>
  <li>Item 2</li>
</ul>
<img src="image.png">
```

**Environment:**
 - OS: macOS
 - Version: 1.1

**Additional context**

The problem has to do with the underlying parseString function unable to handle void tags:

```python
from xml.dom.minidom import parseString as string_to_dom
string_to_dom(html)
```

Possible solution, turn void tags into self-closing tags on input, and the transform them back to void tags on print....

**Comment by mickm3n** [comment]
My thought is to use regex to do string replacement for void tags and add a special attribute as a mark to transform them back. Does it make sense to you?

**Comment by maxhumber** [comment]
I had the same idea `<void a="b">` to `<void a="b" />` back to `<void a="b">` after formatting

**Comment by mickm3n** [comment]
I could work on this.

**Comment by maxhumber** [comment]
Sweet! Looking forward to what you come up with~
