### ISSUE TITLE
separate find into find and find_one

### ISSUE THREAD

**Issue by maxhumber** [maxhumber/gazpacho#3]
**Is your feature request related to a problem? Please describe.**
Right now it's hard to reason about the behaviour of the `find` method. If it finds one element it will return a `Soup` object, if it finds more than one it will return a list of `Soup` objects.

**Describe the solution you'd like**
Separate `find` into a `find` method and `find_one` method.

**Describe alternatives you've considered**
Keep it and YOLO?

**Additional context**
Conversation with Michael Kennedy:

> If I were designing the api, i'd have that always return a List[Node]  (or whatever the class is). Then add two methods:
>  
> * find() -> List[Node]
> * find_one() -> Optional[Node]
> * one() -> Node (exception if the there are zero or two or more nodes)

**Comment by OsamaNabih** [comment]
I'll get to it.

**Comment by maxhumber** [comment]
I have a rough idea that I've been sketching in the [0.8 branch](https://github.com/maxhumber/gazpacho/blob/0.8/gazpacho/soup.py) but it's not very DRY and I'm not convinced it's the best way to do it (yet)...

**Comment by maxhumber** [comment]
Having second thoughts. I think find should have a mode argument: {'auto', 'all', 'first'}...

**Comment by maxhumber** [comment]
Find mode added to [v0.8](https://github.com/maxhumber/gazpacho/releases/tag/v0.8)
