### ISSUE TITLE
Stacktoberfest

### ISSUE THREAD

**Issue by maxhumber** [maxhumber/gazpacho#32]
### #Stacktoberfest 

Introducing a campaign that I'm calling #Stacktoberfest 🥫

If you're a fan of `gazpacho` and want to help evangelize the package, this campaign is for you!

### Question Bank

I've created a [question bank](https://github.com/maxhumber/gazpacho/blob/master/STACKOVERFLOW.md) and have already committed ~30 answers myself.

There are several questions in the bank that I still think deserve modern `gazpacho` answers. 

### Contributing

If you decide to answer any of the questions in the bank (or find another one that you think deserves a `gazpacho` answer, please submit a PR with a link to your answer!

Importantly, these answers should be **high quality** (we want to convince users that `gazpacho` > `bs4`), **respectful**, and the **opposite of obnoxious**.

### Example

I found [this](https://stackoverflow.com/questions/18966368/python-beautifulsoup-scrape-tables/) question by searching for popular `[web-scraping], [python]` questions. It has 55k views, 19 upvotes and the original link is dead. Given that it gets a lot of traffic, I thought it deserved a new modern answer... here it is:

---

The original link posted by OP is dead... but here's how you might scrape table data with gazpacho:

Step 1 - import Soup and download the html:

```python
from gazpacho import Soup

url = "https://en.wikipedia.org/wiki/List_of_multiple_Olympic_gold_medalists"
soup = Soup.get(url)
```

Step 2 - Find the table and table rows:

```python
table = soup.find("table", {"class": "wikitable sortable"}, mode="first")
trs = table.find("tr")[1:]
```

Step 3 - Parse each row with a function to extract desired data:

```python
def parse_tr(tr):
    return {
        "name": tr.find("td")[0].text,
        "country": tr.find("td")[1].text,
        "medals": int(tr.find("td")[-1].text)
    }

data = [parse_tr(tr) for tr in trs]
sorted(data, key=lambda x: x["medals"], reverse=True)
```

---

Looking forward to your contributions!

**Comment by Curious-Ujjwal** [comment]
I also like to contribute my <b>gazpacho</b> answers to the unanswered questions.
Can you tell what does this 🥫 mean in the Answer column?

**Comment by maxhumber** [comment]
Answered with a gazpacho answer! (Soup can emoji 😉)
