### ISSUE TITLE
.text returns nested data instead of trailing data

### ISSUE THREAD

**Issue by sorasful** [maxhumber/gazpacho#34]
**Describe the bug**
When trying to get text from a <a> tag, gazpacho returns empty string

**To Reproduce**
Code to reproduce the behaviour:

```python
from gazpacho import Soup

html  = '<a href="/Sorasful?source=gig_cards&referrer_gig_slug=edit-mixing-and-mastering&ref_ctx_id=42d34014-b499-46fa-a1d3-04318b12fecc" rel="nofollow noopener noreferrer" target="_self"><span>by </span>Sorasful</a>'

soup = Soup(html)

print(soup.text)
# prints nothing

print(soup.find('a').text)
# prints "by"


```

**Expected behavior**
Should return "by Sorasful"

**Environment:**
 - OS: Windows 10
 - Version: Python3.8

**Comment by maxhumber** [comment]
Actually, this is correct behaviour. If you want "by Sorasful" try `.strip`:

```python
soup.find("a").strip()
```

**Comment by maxhumber** [comment]
Concerning your first point:

```python
print(soup.text)
# prints nothing
```

This is being worked on in #28 but could use some help!

**Comment by sorasful** [comment]
Why does 

```python
soup.find("a").text.strip()
``` 

Returns only "by" ? It should return the content of a tag I believe

**Comment by maxhumber** [comment]
Hmm. You're actually right 😬

The first issue has been fixed in #29.

But, I think:

```python
print(soup.find('a').text)
```

Should return just `Sorasful` and not `by` or `by Sorasful`

**Comment by vyshakhj** [comment]
`Should return just Sorasful and not by or by Sorasful` 

Can you please explain why?

**Comment by sorasful** [comment]
I think he meant this because actually the a tag just contains Sorasful text, even though there is a span in it.
