### ISSUE TITLE
Help with mocking network (get) tests

### ISSUE THREAD

**Issue by maxhumber** [maxhumber/gazpacho#37]
**Is your feature request related to a problem? Please describe.**

Right now gazpacho has to hit various websites in it's test suite to make sure everything works, including:

- https://en.wikipedia.org/
- https://httpbin.org/
- https://httpstat.us/

**Describe the solution you'd like**

These tests should really be mocked.

**Additional context**

Could use some help on doing this properly!

**Comment by saibot94** [comment]
Hi! I believe patching would do the trick to avoid doing actual HTTP calls. I'll submit an MR.

**Comment by maxhumber** [comment]
Agreed! Looking forward to what you come up with 👍
