### ISSUE TITLE
User Agent Rotation / Faking

### ISSUE THREAD

**Issue by maxhumber** [maxhumber/gazpacho#39]
**Is your feature request related to a problem? Please describe.**

It might be nice if gazpacho had the ability to rotate/fake a user agent

**Describe the solution you'd like**

Sort of like [this](https://github.com/hellysmile/fake-useragent) but more primitive. (Importantly gazpacho does not want to take on any dependencies)

**Additional context**

Right now gazpacho just spoofs the latest Firefox User Agent

**Comment by am401** [comment]
Hello there! I would like to work on this if it's possible to assign to me. Were you looking to add a number of User Agents in to the main body of the script or look at using an external file?

**Comment by maxhumber** [comment]
Yours! And I don't have an opinion (yet 😏) perhaps as it comes together the right way will be obvious. I'd be interested to see what you come up with and your rationale behind it~

**Comment by am401** [comment]
@maxhumber #44 is my current take on it using a fixed number of hard coded UAs. the UA's can be changed, I just picked those out of a random list as such to test.

Setting up a simple script just to run `get` on a URL, I was able to confirm that I am seeing a random UA used. Increasing the list will increase the pool that you can use for UAs.
