### ISSUE TITLE
Enable strict matching for find

### ISSUE THREAD

**Issue by maxhumber** [maxhumber/gazpacho#4]
**Describe the bug**
Right now `match` has an ability to be strict. This functionality is presently not enable for `find`.

**To Reproduce**
Code to reproduce the behaviour:

```python
from gazpacho import Soup, match

match({'foo': 'bar'}, {'foo': 'bar baz'})
# True

match({'foo': 'bar'}, {'foo': 'bar baz'}, strict=True)
# False
```

**Expected behavior**
The `find` method should be forgiving (partial match) to protect ease of use, and maintain backwards compatibility, but there *should* be an argument to enable strict/exact matching that piggybacks on `match`

**Environment:**
 - OS: macOS
 - Version: 0.7.2

**Comment by kauziishere** [comment]
I can get on this one.

**Comment by maxhumber** [comment]
Hey @kauziishere I think I might have got it in my [0.8](https://github.com/maxhumber/gazpacho/tree/0.8) candidate branch.

**Comment by maxhumber** [comment]
Enabled in [v0.8](https://github.com/maxhumber/gazpacho/releases/tag/v0.8)
