### ISSUE TITLE
Pls make `find()` always return a list

### ISSUE THREAD

**Issue by weiss-d** [maxhumber/gazpacho#50]
Hi! This library is cool, but I've started using it and immediately stumbled upon one difficulty:
`Soup.find()` returns a `list` of `Soup`s if it finds multiple tags, a single `Soup` object if it finds single tag, and `None` if it finds no tags.
This makes impossible to seamlessly use `find()` in `for` expressions and comprehensions like one in the "Books" example.

Imagine, I need to parse multiple pages, each one containing unknown ammount of books in 0 to N range.
To make it seamlessly I need to write 3-branch `if` expression or somehow catch the `TypeError` with nested `try` blocks.

This is what happens with the example when it finds only one book:
```python
In [7]: from gazpacho import get, Soup
   ...: 
   ...: url = 'https://scrape.world/books'
   ...: html = get(url)
   ...: soup = Soup(html)
   ...: books = soup.find('div', {'class': 'book-early'})
   ...: 
   ...: def parse(book):
   ...:     name = book.find('h4').text
   ...:     price = float(book.find('p').text[1:].split(' ')[0])
   ...:     return name, price
   ...: 
   ...: [parse(book) for book in books]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-16cc6dbabde2> in <module>
     11     return name, price
     12 
---> 13 [parse(book) for book in books]

TypeError: 'Soup' object is not iterable
```
So, could you please make `find()` return an **empty list if no tags**, and a **list with one element if only one tag** is found?

**Comment by scrambldchannel** [comment]
Hi Simon

I've only just started using gazpacho too but I think you want to experiment with passing the mode parameter to the find method. Eg, instead of:

```python 
book.find('p')
```
Use:

```python
book.find('p', mode="all")
```

As far as I can tell, this will give you a list irrespective of how many paragraph tags are found. There's a tiny bit in the docs here - https://gazpacho.xyz/#mode
 
Hopefully that helps

**Comment by weiss-d** [comment]
Thanks, @scrambldchannel! This does exactly what I need.
