### ISSUE TITLE
Get all the child elements of a Soup object

### ISSUE THREAD

**Issue by Vthechamp22** [maxhumber/gazpacho#56]
**Is your feature request related to a problem? Please describe.**
I would like try to a `.children()` method in the Soup object that can list all the child elements of the `Soup` object.

**Describe the solution you'd like**
I would make a regex pattern to match each inner element and return a list of `Soup()` objects with those elements. I might also try to make an option for recurse or not.

**Describe alternatives you've considered**
All that I can think of is doing the same thing mentioned above in the scraping code

**Additional context**
None

**Comment by Vthechamp22** [comment]
Can I work on this if this is approved too?

**Comment by maxhumber** [comment]
Thanks for the suggestion! It's a nice idea, but goes against the core of what gazpacho wants to be (see #33 for a related discussion). 

Basically, having `find` be the only way to interact with the API is a "Constrains + Gains" situation. If users need something beyond `find`, gazpacho is happy to defer to bs4.
