### ISSUE TITLE
Find the parent of a node

### ISSUE THREAD

**Issue by edkrueger** [maxhumber/gazpacho#64]
## Is your feature request related to a problem? Please describe.
I would like to be able to find the parent of a node.

## Describe the solution you'd like
I think `soup.parent` would be a nice UI.
For example if we have:
```
<ul>
     <li class="my-class"></li>
</ul>
```
We can get the ul tag with `ul_tag = soup.find("li", attrs={"class": "my-class").parent`

## Describe alternatives you've considered
An alternative would be some nested filtering perhaps like:
```
li = soup.find("li", "my-class")
ul = soup.find("ul", with_child=li)
```

## Additional information
Thanks for your work on the package!

**Comment by maxhumber** [comment]
A great idea, but out of scope for now. Would require a full rewrite of the package :(
