### ISSUE TITLE
Proxies

### ISSUE THREAD

**Issue by bjquinniii** [maxhumber/gazpacho#65]
## Is your feature request related to a problem? Please describe.
Really just a question, followed by a request. Does gazpacho currently support the use of proxies? (If not, would be great to include).

**Comment by maxhumber** [comment]
Thanks for the suggestion. I'm going to make this as out of scope. Would require a ton of work for not much gain. gazpacho is a tool for 95% of your web scraping needs. I'll leave the other 5% to other tools!
