### ISSUE TITLE
A select function similar to soups.

### ISSUE THREAD

**Issue by kjaymiller** [maxhumber/gazpacho#9]
**Is your feature request related to a problem? Please describe.**
It's great to be able to run find and then find within the initial result, but it seems more readable to be able to find based on CSS selectors.

**Describe the solution you'd like**
```
selector = '.foo img.bar'
soup.select(selector) # this would return any img item with the class "bar" inside of an object with the class "foo"
```

**Comment by maxhumber** [comment]
@kjaymiller thanks for your request! It's a nice idea, and one that I've toyed with... However, I'm hesitant to add CSS selectors at this moment because they're not exactly intuitive/user-friendly for those who don't know front-end (the bulk of gazpacho users right now). And they wouldn't provide all that much more over the existing `find` method. That said, if CSS selectors keep coming up perhaps we can we revisit this in the future. But for now I'm going to close this.

**Comment by simonw** [comment]
I came here to request CSS selector support too - every scraper I've written in the past decade has worked using CSS selectors and I honestly can't imagine scraping without them.

I wrote the first library that added selector support to BeautifulSoup (before it was a built-in feature) - the implementation wasn't too complicated, you're welcome to borrow from it if it looks useful: https://github.com/simonw/soupselect

**Comment by maxhumber** [comment]
Super slick! A non-negotiable for me is that gazpacho remain 0 dependency. But it's cool to see such a clean pure python way of implementing selectors.

**Comment by maxhumber** [comment]
My hesitation in adding selectors is that I think the overlap between people who know them and Python Developers/Data Scientists/Data Engineers is smaller than we realize. I've been scraping for like 4 years now, and I still don't really understand them 🙈 

I don't want `gazpacho` to replace bs4/lxml for everything. I want it to be the hammer that solves 95% of your web scraping problems. If that makes sense?

**Comment by simonw** [comment]
My offer here isn't for your to depend on soupselect - which is 14 years old and never saw a release on PyPI. It's for you to copy and paste over the code from that, clean it up and incorporate it into Gazpacho. The key implementation is only 100 lines of Python.
